# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-09 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200, verbose_name='\u0110\xe1p \xe1n')),
                ('votes', models.IntegerField(default=0, verbose_name='S\u1ed1 l\u1ea7n vote')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200, verbose_name='N\u1ed9i dung')),
                ('date_pub', models.DateTimeField(verbose_name='Ng\xe0y c\u1eadp nh\u1eadt')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
    ]
